const countries = [
    {
        key: 0,
        country: "/img/homepage/brazil-.png",
        name: "Portuguese",
        description:  "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/brazilTranslation.jpg",
        background: "/img/translator/cristoredentor.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐",
        months: "12 - 24",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "9TH",
        country1: "/img/homepage/brazil-.png",
        country2: "/img/translator/portugal.png",
        country3: "/img/translator/mozambique.png",
        country4: "/img/translator/angola.png",
    },
    {
        key: 1,
        country: "/img/homepage/united-states.png",
        name: "English",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/englishTranslation.jpg",
        background: "/img/translator/englishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "1TH",
        country1: "/img/homepage/united-states.png",
        country2: "/img/translator/canada.png",
        country3: "/img/translator/australia.png",
        country4: "/img/translator/united-kingdom.png",
    },
    {   
        key: 2,
        country: "/img/homepage/spain.png",
        name: "Spanish",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/SpanishTranslation.jpg",
        background: "/img/translator/spanishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "4TH",
        country1: "/img/homepage/spain.png",
        country2: "/img/translator/argentina.png",
        country3: "/img/translator/colombia.png",
        country4: "/img/translator/mexico.png",
    },
    {
        key: 3,
        country: "/img/homepage/france.png",
        name: "French",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/frenchTranslation.jpg",
        background: "/img/translator/frenchBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "5TH",
        country1: "/img/homepage/france.png",
        country2: "/img/translator/canada.png",
        country3: "/img/translator/belgium.png",
        country4: "/img/translator/luxembourg.png",
    },
    {
        key: 4,
        country: "/img/homepage/italy.png",
        name: "Italian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/italianTranslation.jpg",
        background: "/img/translator/italianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "29TH",
        country1: "/img/homepage/italy.png",
        country2: "/img/translator/switzerland.png",
        country3: "/img/translator/san-marino.png",
        country4: "/img/translator/vatican-city.png",
    },
    {
        key: 5,
        country: "/img/homepage/hungary.png",
        name: "Hungarian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/hungarianTranslation.jpg",
        background: "/img/translator/hungarianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "66TH",
        country1: "/img/homepage/hungary.png",
        country2: "/img/translator/serbia.png",
        country3: "/img/translator/slovakia.png",
        country4: "/img/translator/romania.png",
    },
    {
        key: 6,
        country: "/img/homepage/ukraine.png",
        name: "Ukranian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/ukranianTranslation.jpg",
        background: "/img/translator/ukranianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "30TH",
        country1: "/img/homepage/ukraine.png",
        country2: "/img/translator/moldova.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/homepage/poland.png",
    },
    {
        key: 7,
        country: "/img/homepage/russia.png",
        name: "Russian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        reachness: "8TH",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",

    },
    {
        key: 8,
        country: "/img/homepage/poland.png",
        name: "Polish",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/polishTranslation.jpg",
        background: "/img/translator/polishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "29TH",
        country1: "/img/homepage/poland.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/homepage/russia.png",
    },
    {
        key: 9,
        country: "/img/homepage/germany.png",
        name: "German",
        description: "In the whispers of German, every syllable carries a profound significance, akin to ancient glyphs inscribed upon the annals of time, each imbued with an intricate beauty. Its consonants resonate like the solemn toll of cathedral bells, echoing through the corridors of history, orchestrating a symphony that spans epochs.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/germanTranslation.jpg",
        background: "/img/translator/germanyBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “Home of the incomprehensible. a unexpected beauty spreading in the air ”. ",
        reachness: "12TH",
        country1: "/img/homepage/germany.png",
        country2: "/img/translator/austria.png",
        country3: "/img/translator/switzerland.png",
        country4: "/img/translator/luxembourg.png",
    },
    {
        key: 10,
        country: "/img/homepage/netherlands.png",
        name: "Dutch",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/dutchTranslation.jpg",
        background: "/img/translator/dutchBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "52TH",
        country1: "/img/homepage/netherlands.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 11,
        country: "/img/homepage/greece.png",
        name: "Greek",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/greekTranslation.jpg",
        background: "/img/translator/greekBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "68TH",
        country1: "/img/homepage/greece.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 12,
        country: "/img/homepage/norway.png",
        name: "Norwegian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/norwegianTranslation.jpg",
        background: "/img/translator/norwegianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "55TH",
        country1: "/img/homepage/norway.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 13,
        country: "/img/homepage/denamark.png",
        name: "Danish",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/danishTranslation.jpg",
        background: "/img/translator/danish.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "50TH",
        country1: "/img/homepage/denamark.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 14,
        country: "/img/homepage/saudi-arabia.png",
        name: "Arabic",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/arabicTranslation.jpg",
        background: "/img/translator/arabicBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐⭐",
        months: "48 - 72",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "6TH",
        country1: "/img/homepage/saudi-arabia.png",
        country2: "/img/translator/egypt.png",
        country3: "/img/translator/iran.png",
        country4: "/img/translator/morocco.png",
    },
    {
        key: 15,
        country: "/img/homepage/turkey.png",
        name: "Turkish",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/turkishTranslation.jpg",
        background: "/img/translator/turkishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "17TH",
        country1: "/img/homepage/turkey.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 16,
        country: "/img/homepage/china.png",
        name: "Chinese",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/chinaTranslation.jpg",
        background: "/img/translator/chineseBackground.png",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐⭐",
        months: "60 - 84",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "2TH",
        country1: "/img/homepage/china.png",
        country2: "/img/translator/hong-kong.png",
        country3: "/img/translator/macau.png",
        country4: "/img/translator/taiwan.png",
    },
    {
        key: 17,
        country: "/img/homepage/japan.png",
        name: "Japanese",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translation: "Русский язык — это славянский язык, который является официальным языком в России, Беларуси, Казахстане и Кыргызстане, а также одним из официальных языков в ряде других стран. Он имеет богатую историю, включая различные диалекты и влияние различных культур.",
        translationBackground: "/img/translator/japaneseTranslation.jpg",
        background: "/img/translator/japaneseBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "13TH",
        country1: "/img/homepage/japan.png",
        country2: "/img/homepage/brazil-.png",
        country3: "/img/homepage/united-states.png",
        country4: "/img/translator/canada.png",
    },
]

export default countries;
