const countries = [
    {
        key: 0,
        country: "/img/homepage/brazil-.png",
        name: "Portuguese",
        description:  "PORTUGUESE IS A ROMANCE LANGUAGE THAT IS THE OFFICIAL LANGUAGE IN PORTUGAL, BRAZIL, MOZAMBIQUE, ANGOLA, GUINEA-BISSAU, EAST TIMOR, EQUATORIAL GUINEA, AND CAPE VERDE, AS WELL AS ONE OF THE OFFICIAL LANGUAGES IN MACAU. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM DIFFERENT CULTURES.",
        translationBackground: "/img/translator/brazilTranslation.jpg",
        background: "/img/translator/cristoredentor.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐",
        months: "12 - 24",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "9TH",
        country1: "/img/homepage/brazil-.png",
        country2: "/img/translator/portugal.png",
        country3: "/img/translator/mozambique.png",
        country4: "/img/translator/angola.png",
    },
    {
        key: 1,
        country: "/img/homepage/united-states.png",
        name: "English",
        description: "ENGLISH IS A GERMANIC LANGUAGE THAT IS THE OFFICIAL LANGUAGE IN THE UNITED KINGDOM, THE UNITED STATES, CANADA, AUSTRALIA, AND NEW ZEALAND, AS WELL AS ONE OF THE OFFICIAL LANGUAGES IN MANY OTHER COUNTRIES. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM DIFFERENT CULTURES.",
        translationBackground: "/img/translator/englishTranslation.jpg",
        background: "/img/translator/englishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "1TH",
        country1: "/img/homepage/united-states.png",
        country2: "/img/translator/canada.png",
        country3: "/img/translator/australia.png",
        country4: "/img/translator/united-kingdom.png",
    },
    {
        key: 2,
        country: "/img/homepage/spain.png",
        name: "Spanish",
        description: "SPANISH IS A ROMANCE LANGUAGE THAT IS THE OFFICIAL LANGUAGE IN SPAIN, MOST OF LATIN AMERICA, AND EQUATORIAL GUINEA, AS WELL AS ONE OF THE OFFICIAL LANGUAGES OF THE UNITED NATIONS. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM DIFFERENT CULTURES.",
        translationBackground: "/img/translator/spanishTranslation.jpg",
        background: "/img/translator/spanishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "4TH",
        country1: "/img/homepage/spain.png",
        country2: "/img/translator/argentina.png",
        country3: "/img/translator/colombia.png",
        country4: "/img/translator/mexico.png",
    },
    {
        key: 3,
        country: "/img/homepage/france.png",
        name: "French",
        description:"FRENCH IS A ROMANCE LANGUAGE THAT IS THE OFFICIAL LANGUAGE IN FRANCE, CANADA (PARTICULARLY QUEBEC), BELGIUM, SWITZERLAND, AND SEVERAL AFRICAN COUNTRIES, AS WELL AS ONE OF THE OFFICIAL LANGUAGES OF THE UNITED NATIONS AND THE EUROPEAN UNION. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM DIFFERENT CULTURES.",
        translationBackground: "/img/translator/frenchTranslation.jpg",
        background: "/img/translator/frenchBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "5TH",
        country1: "/img/homepage/france.png",
        country2: "/img/translator/canada.png",
        country3: "/img/translator/belgium.png",
        country4: "/img/translator/luxembourg.png",
    },
    {
        key: 4,
        country: "/img/homepage/italy.png",
        name: "Italian",
        description: "ITALIAN IS A ROMANCE LANGUAGE THAT IS THE OFFICIAL LANGUAGE IN ITALY, SAN MARINO, SWITZERLAND (TICINO AND GRAUBÜNDEN), VATICAN CITY, AND SOME REGIONS OF CROATIA AND SLOVENIA. IT IS ALSO SPOKEN BY MINORITIES IN ALBANIA, MALTA, MONACO, AND FRANCE. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM DIFFERENT CULTURES.",
        translationBackground: "/img/translator/italianTranslation.jpg",
        background: "/img/translator/italianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "29TH",
        country1: "/img/homepage/italy.png",
        country2: "/img/translator/switzerland.png",
        country3: "/img/translator/san-marino.png",
        country4: "/img/translator/vatican-city.png",
    },
    {
        key: 5,
        country: "/img/homepage/hungary.png",
        name: "Hungarian",
        description: "HUNGARIAN IS A FINNO-UGRIC LANGUAGE SPOKEN PRIMARILY IN HUNGARY. IT IS ALSO SPOKEN BY COMMUNITIES IN AREAS SUCH AS ROMANIA, SLOVAKIA, SERBIA, UKRAINE, CROATIA, AUSTRIA, AND SLOVENIA. IT HAS A RICH HISTORY, INCLUDING INFLUENCES FROM VARIOUS NEIGHBORING LANGUAGES AND CULTURES.",
        translationBackground: "/img/translator/hungarianTranslation.jpg",
        background: "/img/translator/hungarianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "66TH",
        country1: "/img/homepage/hungary.png",
        country2: "/img/translator/serbia.png",
        country3: "/img/translator/slovakia.png",
        country4: "/img/translator/romania.png",
    },
    {
        key: 6,
        country: "/img/homepage/ukraine.png",
        name: "Ukranian",
        description: "UKRAINIAN IS A SLAVIC LANGUAGE SPOKEN PRIMARILY IN UKRAINE. IT IS ALSO SPOKEN BY COMMUNITIES IN NEIGHBORING COUNTRIES SUCH AS RUSSIA, BELARUS, POLAND, AND SLOVAKIA. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM DIFFERENT CULTURES.",
        translationBackground: "/img/translator/ukranianTranslation.jpg",
        background: "/img/translator/ukranianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "30TH",
        country1: "/img/homepage/ukraine.png",
        country2: "/img/translator/moldova.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/homepage/poland.png",
    },
    {
        key: 7,
        country: "/img/homepage/russia.png",
        name: "Russian",
        description: "Russian is a Slavic language that is the official language in Russia, Belarus, Kazakhstan and Kyrgyzstan, as well as one of the official languages in several other countries. It has a rich history, including different dialects and influences from different cultures.",
        translationBackground: "/img/translator/russianTranslationBackground.jpg",
        background: "/img/translator/russiaBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        reachness: "8TH",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        country1: "/img/homepage/russia.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",

    },
    {
        key: 8,
        country: "/img/homepage/poland.png",
        name: "Polish",
        description: "POLISH IS A SLAVIC LANGUAGE SPOKEN PRIMARILY IN POLAND. IT IS ALSO SPOKEN BY COMMUNITIES IN OTHER COUNTRIES SUCH AS THE UNITED STATES, CANADA, THE UNITED KINGDOM, GERMANY, AND AUSTRALIA. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM VARIOUS NEIGHBORING LANGUAGES AND CULTURES.",
        translationBackground: "/img/translator/polishTranslation.jpg",
        background: "/img/translator/polishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "29TH",
        country1: "/img/homepage/poland.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/homepage/russia.png",
    },
    {
        key: 9,
        country: "/img/homepage/germany.png",
        name: "German",
        description: "GERMAN IS A WEST GERMANIC LANGUAGE SPOKEN PRIMARILY IN GERMANY, AUSTRIA, SWITZERLAND, LUXEMBOURG, AND LIECHTENSTEIN. IT IS ALSO SPOKEN BY MINORITIES IN OTHER EUROPEAN COUNTRIES AND COMMUNITIES AROUND THE WORLD. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM VARIOUS LANGUAGES AND CULTURES.",
        translationBackground: "/img/translator/germanTranslation.jpg",
        background: "/img/translator/germanyBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “Home of the incomprehensible. a unexpected beauty spreading in the air ”. ",
        reachness: "12TH",
        country1: "/img/homepage/germany.png",
        country2: "/img/translator/austria.png",
        country3: "/img/translator/switzerland.png",
        country4: "/img/translator/luxembourg.png",
    },
    {
        key: 10,
        country: "/img/homepage/netherlands.png",
        name: "Dutch",
        description: "DUTCH IS A WEST GERMANIC LANGUAGE SPOKEN PRIMARILY IN THE NETHERLANDS, BELGIUM, SURINAME, AND PARTS OF THE CARIBBEAN. IT IS ALSO SPOKEN BY COMMUNITIES IN NEIGHBORING COUNTRIES SUCH AS GERMANY AND FRANCE. IT HAS A RICH HISTORY, INCLUDING DIFFERENT DIALECTS AND INFLUENCES FROM VARIOUS LANGUAGES AND CULTURES.",
        translationBackground: "/img/translator/dutchTranslation.jpg",
        background: "/img/translator/dutchBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "52TH",
        country1: "/img/homepage/netherlands.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 11,
        country: "/img/homepage/greece.png",
        name: "Greek",
        description: "GREEK IS AN INDO-EUROPEAN LANGUAGE SPOKEN PRIMARILY IN GREECE AND CYPRUS. IT IS ALSO SPOKEN BY MINORITIES IN ALBANIA, ITALY, TURKEY, AND OTHER PARTS OF THE WORLD. IT HAS A LONG AND RICH HISTORY, WITH INFLUENCES FROM ANCIENT GREEK, LATIN, AND OTHER LANGUAGES.",
        translationBackground: "/img/translator/greekTranslation.jpg",
        background: "/img/translator/greekBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "68TH",
        country1: "/img/homepage/greece.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 12,
        country: "/img/homepage/norway.png",
        name: "Norwegian",
        description: "NORWEGIAN IS A NORTH GERMANIC LANGUAGE SPOKEN PRIMARILY IN NORWAY. IT HAS TWO WRITTEN FORMS: BOKMÅL AND NYNORSK. IT IS ALSO SPOKEN BY NORWEGIAN COMMUNITIES IN OTHER COUNTRIES, SUCH AS THE UNITED STATES AND SWEDEN. IT HAS A RICH HISTORY, WITH INFLUENCES FROM OLD NORSE AND OTHER SCANDINAVIAN LANGUAGES.",
        translationBackground: "/img/translator/norwegianTranslation.jpg",
        background: "/img/translator/norwegianBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "55TH",
        country1: "/img/homepage/norway.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 13,
        country: "/img/homepage/denamark.png",
        name: "Danish",
        description: "DANISH IS A NORTH GERMANIC LANGUAGE SPOKEN PRIMARILY IN DENMARK. IT IS ALSO SPOKEN BY COMMUNITIES IN PARTS OF GERMANY AND GREENLAND. IT HAS A CLOSE RELATIONSHIP WITH NORWEGIAN AND SWEDISH, AND SHARES SIMILARITIES WITH THESE LANGUAGES.",
        translationBackground: "/img/translator/danishTranslation.jpg",
        background: "/img/translator/danish.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "50TH",
        country1: "/img/homepage/denamark.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 14,
        country: "/img/homepage/saudi-arabia.png",
        name: "Arabic",
        description: "ARABIC IS A SEMITIC LANGUAGE SPOKEN PRIMARILY IN THE ARAB WORLD, INCLUDING COUNTRIES SUCH AS EGYPT, SAUDI ARABIA, IRAQ, SYRIA, AND MOROCCO. IT IS ALSO SPOKEN BY COMMUNITIES IN OTHER PARTS OF THE WORLD, PARTICULARLY IN AFRICA AND ASIA. IT HAS A RICH HISTORY, WITH VARIOUS DIALECTS AND INFLUENCES FROM ANCIENT LANGUAGES SUCH AS ARAMAIC AND HEBREW.",
        translationBackground: "/img/translator/arabicTranslation.jpg",
        background: "/img/translator/arabicBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐⭐",
        months: "48 - 72",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "6TH",
        country1: "/img/homepage/saudi-arabia.png",
        country2: "/img/translator/egypt.png",
        country3: "/img/translator/iran.png",
        country4: "/img/translator/morocco.png",
    },
    {
        key: 15,
        country: "/img/homepage/turkey.png",
        name: "Turkish",
        description: "TURKISH IS A TURKIC LANGUAGE SPOKEN PRIMARILY IN TURKEY AND CYPRUS. IT IS ALSO SPOKEN BY TURKISH COMMUNITIES IN OTHER COUNTRIES, SUCH AS GERMANY, BULGARIA, AND GREECE. IT HAS A RICH HISTORY, WITH INFLUENCES FROM VARIOUS LANGUAGES AND CULTURES, INCLUDING ARABIC, PERSIAN, AND EUROPEAN LANGUAGES.",
        translationBackground: "/img/translator/turkishTranslation.jpg",
        background: "/img/translator/turkishBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "17TH",
        country1: "/img/homepage/turkey.png",
        country2: "/img/translator/ukraine.png",
        country3: "/img/translator/kazakhstan.png",
        country4: "/img/translator/belarus.png",
    },
    {
        key: 16,
        country: "/img/homepage/china.png",
        name: "Chinese",
        description: "CHINESE IS A SINO-TIBETAN LANGUAGE SPOKEN PRIMARILY IN CHINA, WHERE IT IS THE OFFICIAL LANGUAGE, AND ALSO IN TAIWAN, SINGAPORE, AND OTHER PARTS OF THE CHINESE DIASPORA. IT IS ONE OF THE MOST SPOKEN LANGUAGES IN THE WORLD. CHINESE INCLUDES NUMEROUS DIALECTS, THE MOST PROMINENT BEING MANDARIN, AND HAS A RICH HISTORY THAT SPANS THOUSANDS OF YEARS.",
        translationBackground: "/img/translator/chinaTranslation.jpg",
        background: "/img/translator/chineseBackground.png",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐⭐",
        months: "60 - 84",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "2TH",
        country1: "/img/homepage/china.png",
        country2: "/img/translator/hong-kong.png",
        country3: "/img/translator/macau.png",
        country4: "/img/translator/taiwan.png",
    },
    {
        key: 17,
        country: "/img/homepage/japan.png",
        name: "Japanese",
        description: "JAPANESE IS A JAPONIC LANGUAGE SPOKEN PRIMARILY IN JAPAN. IT IS ALSO SPOKEN BY JAPANESE COMMUNITIES IN OTHER PARTS OF THE WORLD. IT HAS A UNIQUE WRITING SYSTEM THAT INCLUDES HIRAGANA, KATAKANA, AND CHINESE CHARACTERS KNOWN AS KANJI. JAPANESE HAS A RICH HISTORY, WITH INFLUENCES FROM CHINESE, KOREAN, AND OTHER LANGUAGES.",
        translationBackground: "/img/translator/japaneseTranslation.jpg",
        background: "/img/translator/japaneseBackground.jpg",
        culture:"/img/translator/russiaCulture.jpg",
        challenge:"⭐⭐⭐⭐⭐",
        months: "24 - 36",
        review: " “A huge language! There is Always a richness being expressed ”. ",
        reachness: "13TH",
        country1: "/img/homepage/japan.png",
        country2: "/img/homepage/brazil-.png",
        country3: "/img/homepage/united-states.png",
        country4: "/img/translator/canada.png",
    },
]

export default countries;
